#!/bin/bash

set -e

base="$(basename "$0")"

if [ $# -eq 0 ]; then
  printf "usage: $base host:port\n"
  exit 1
fi

host=$(printf "$1" | awk -F: '{printf $1}')
port=$(printf "$1" | awk -F: '{printf $2}')

if [ -n "$port" ]; then
  port="and port $port"
fi

sudo tcpdump "host $host $port" -w - | tcptrace -l -r stdin

